name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Solution
      run: dotnet build --no-restore
    - name: Run Test
      run: dotnet test --no-build --verbosity normal
      
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      -
        name: DockerHub Login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Backend
        run: docker build . -t yzbrian/all-in-1-planning:dev
        working-directory: .

      - name: Push Backend
        run: docker push yzbrian/all-in-1-planning:dev
        working-directory: .
